name: CI
on: [push]

jobs:
  general-ci:
    runs-on: ubuntu-latest
    container: node:16

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build

    - name: Typecheck
      run: npm run tsc
    
    - name: Lint
      run: npm run lint
